framework:
    secret: '%env(APP_SECRET)%'
    handle_all_throwables: true
    http_method_override: false
    http_cache: true
    
    php_errors:
        log: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    validation:
        enable_attributes: true

    serializer:
        enable_attributes: true

    property_access: ~
    property_info:
        enabled: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file