
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: fruits-and-vegetables-challenge-php
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    working_dir: /var/www/html
    networks:
      - fruits_vegetables_network
    environment:
      - APP_ENV=dev
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_MEMORY_CONSUMPTION=256
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=20000

  nginx:
    image: nginx:alpine
    container_name: fruits_vegetables_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - fruits_vegetables_network

networks:
  fruits_vegetables_network:
    driver: bridge

volumes:
  vendor:
    driver: local